{% set name = "pgure-svt" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tjof2/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9ef8a8b6e2fe9ffdb28042f5ae1a9055a722fcce53a4cc132ba0c772de2d6d75
  patches:
    - march.patch  # [not win]
    - 0001-Fix-flags-for-MSVC.patch  # [win]

build:
  number: 10
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - armadillo
    - cython
    - liblapack
    - nlopt
    - numpy
    - pip
    - python
    - setuptools
  run:
    - armadillo
    - liblapack
    - nlopt
    - python

test:
  imports:
    - pguresvt.svt
    - pguresvt.hspy

about:
  home: https://github.com/tjof2/pgure-svt
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Singular value thresholding for denoising time-resolved microscopy
  description: |
    PGURE-SVT (Poisson-Gaussian Unbiased Risk Estimator - Singular Value Thresholding) is an algorithm designed to denoise image sequences acquired in microscopy. It exploits the correlations between consecutive frames to form low-rank matrices, which are then recovered using a technique known as nuclear norm minimization. An unbiased risk estimator for mixed Poisson-Gaussian noise is used to automate the selection of the regularization parameter, while robust noise and motion estimation maintain broad applicability to many different types of microscopy.
  doc_url: https://github.com/tjof2/pgure-svt
  dev_url: https://github.com/tjof2/pgure-svt

extra:
  recipe-maintainers:
    - ericpre
    - tjof2
